FROM ubuntu:groovy

MAINTAINER mark1626

RUN apt update
RUN	apt install -y vim tmux zsh \
                    clang clang-format cmake \
                    linux-tools-common \
                    linux-tools-generic \
                    valgrind

WORKDIR /home/mark1626
